import type {
  Equipment,
  MuscleGroup,
  Difficulty,
  MovementPattern,
  UserEquipment,
} from "@/types/database";

export interface Exercise {
  id: string;
  name: string;
  primaryMuscle: MuscleGroup;
  secondaryMuscles: MuscleGroup[];
  equipment: Equipment[];
  difficulty: Difficulty;
  movementPattern: MovementPattern;
  category: "compound" | "isolation";
  instructions: string;
  tips: string;
  alternatives: string[];
  tags: string[];
}

export const EXERCISES: Exercise[] = [
  // ─── CHEST ────────────────────────────────────────────────
  {
    id: "bench_press",
    name: "Barbell Bench Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    movementPattern: "push",
    category: "compound",
    instructions: "Lie flat on the bench, grip the bar slightly wider than shoulder-width. Lower the bar to your chest under control, then press back up explosively.",
    tips: "Keep your feet flat on the floor, maintain a slight arch in your lower back, and retract your shoulder blades.",
    alternatives: ["db_bench_press", "machine_chest_press", "push_up"],
    tags: ["chest", "push", "compound"],
  },
  {
    id: "db_bench_press",
    name: "Dumbbell Bench Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    movementPattern: "push",
    category: "compound",
    instructions: "Lie flat on the bench with a dumbbell in each hand. Press the dumbbells up and slightly inward, then lower with control.",
    tips: "Greater range of motion than barbell. Keep wrists neutral.",
    alternatives: ["bench_press", "machine_chest_press", "incline_db_press"],
    tags: ["chest", "push", "compound"],
  },
  {
    id: "incline_bench",
    name: "Incline Barbell Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    movementPattern: "push",
    category: "compound",
    instructions: "Set bench to 30-45°. Press the bar from your upper chest. Emphasizes upper chest.",
    tips: "Don't go too steep — 30-45° is optimal for upper chest activation.",
    alternatives: ["incline_db_press", "db_bench_press"],
    tags: ["chest", "upper chest", "push"],
  },
  {
    id: "incline_db_press",
    name: "Incline Dumbbell Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    movementPattern: "push",
    category: "compound",
    instructions: "Set bench to 30-45°. Press dumbbells up and together at the top.",
    tips: "Great for upper chest development with better range of motion.",
    alternatives: ["incline_bench", "db_bench_press"],
    tags: ["chest", "upper chest", "push"],
  },
  {
    id: "cable_fly",
    name: "Cable Fly",
    primaryMuscle: "chest",
    secondaryMuscles: [],
    equipment: ["cable"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Set cables at shoulder height. Step forward, arms slightly bent. Bring hands together in a hugging motion.",
    tips: "Constant tension throughout the movement. Squeeze the chest at the peak.",
    alternatives: ["db_fly", "pec_deck"],
    tags: ["chest", "isolation", "cable"],
  },
  {
    id: "db_fly",
    name: "Dumbbell Fly",
    primaryMuscle: "chest",
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Lie flat, arms wide with soft elbow bend. Arc the dumbbells up and together.",
    tips: "Use lighter weight than you think — the stretched position is vulnerable.",
    alternatives: ["cable_fly", "pec_deck"],
    tags: ["chest", "isolation"],
  },
  {
    id: "machine_chest_press",
    name: "Machine Chest Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["machine"],
    difficulty: "beginner",
    movementPattern: "push",
    category: "compound",
    instructions: "Sit in the machine, adjust seat so handles are at chest height. Press forward until arms are extended.",
    tips: "Great for beginners — provides stability so you can focus on the muscle.",
    alternatives: ["db_bench_press", "bench_press"],
    tags: ["chest", "push", "machine"],
  },
  {
    id: "push_up",
    name: "Push Up",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders", "triceps", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    movementPattern: "push",
    category: "compound",
    instructions: "Hands slightly wider than shoulders, body in a plank. Lower chest to floor, press back up.",
    tips: "Keep your core tight and body in a straight line throughout.",
    alternatives: ["db_bench_press", "machine_chest_press"],
    tags: ["chest", "bodyweight", "push"],
  },
  {
    id: "chest_dip",
    name: "Chest Dips",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    movementPattern: "push",
    category: "compound",
    instructions: "Lean forward at 30°, lower until shoulders are below elbows, press back up.",
    tips: "The forward lean targets chest. Upright body targets triceps more.",
    alternatives: ["bench_press", "push_up"],
    tags: ["chest", "bodyweight", "push"],
  },

  // ─── BACK ─────────────────────────────────────────────────
  {
    id: "deadlift",
    name: "Barbell Deadlift",
    primaryMuscle: "back",
    secondaryMuscles: ["hamstrings", "glutes", "traps", "core", "forearms"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    movementPattern: "hinge",
    category: "compound",
    instructions: "Bar over mid-foot, hinge at hips, grip just outside legs. Drive through the floor, keeping bar close to body.",
    tips: "The king of all exercises. Maintain a neutral spine — never round your lower back.",
    alternatives: ["rdl", "trap_bar_deadlift", "db_rdl"],
    tags: ["back", "hinge", "compound", "full body"],
  },
  {
    id: "rdl",
    name: "Romanian Deadlift",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "back", "core"],
    equipment: ["barbell", "dumbbell"],
    difficulty: "intermediate",
    movementPattern: "hinge",
    category: "compound",
    instructions: "Hold bar/dumbbells at hips. Push hips back while lowering the weight along your legs. Stop when you feel a deep hamstring stretch.",
    tips: "Soft knee bend, maintain neutral spine. Feel the hamstrings loading.",
    alternatives: ["leg_curl", "good_morning"],
    tags: ["hamstrings", "hinge", "compound"],
  },
  {
    id: "barbell_row",
    name: "Barbell Row",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps", "traps", "shoulders"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    movementPattern: "pull",
    category: "compound",
    instructions: "Hinge to ~45°, pull the bar to your lower chest/upper abs. Lead with elbows.",
    tips: "Keep your back flat, not rounded. Think about squeezing your elbows together.",
    alternatives: ["db_row", "seated_cable_row", "machine_row"],
    tags: ["back", "pull", "compound"],
  },
  {
    id: "db_row",
    name: "Dumbbell Row",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps", "traps"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    movementPattern: "pull",
    category: "compound",
    instructions: "Support yourself with one hand on bench. Pull dumbbell to your hip, driving elbow straight back.",
    tips: "Excellent for beginners — builds unilateral strength and can train through greater range of motion.",
    alternatives: ["barbell_row", "seated_cable_row", "machine_row"],
    tags: ["back", "pull", "compound"],
  },
  {
    id: "pull_up",
    name: "Pull Up",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps", "core"],
    equipment: ["pullup_bar", "bodyweight"],
    difficulty: "intermediate",
    movementPattern: "pull",
    category: "compound",
    instructions: "Hang with a pronated grip slightly wider than shoulders. Pull until chin clears the bar, lower with control.",
    tips: "Focus on pulling your elbows down and back, not just pulling your chin up.",
    alternatives: ["lat_pulldown", "machine_row"],
    tags: ["back", "bodyweight", "pull", "compound"],
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps"],
    equipment: ["cable"],
    difficulty: "beginner",
    movementPattern: "pull",
    category: "compound",
    instructions: "Wide grip, slight lean back. Pull the bar to your upper chest, leading with your elbows.",
    tips: "Excellent substitute for pull-ups. Focus on pulling through the lats.",
    alternatives: ["pull_up", "machine_row"],
    tags: ["back", "pull", "cable"],
  },
  {
    id: "seated_cable_row",
    name: "Seated Cable Row",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps", "traps"],
    equipment: ["cable"],
    difficulty: "beginner",
    movementPattern: "pull",
    category: "compound",
    instructions: "Sit upright, grip the handle, pull to your lower chest. Don't let your torso rock.",
    tips: "Sit tall and keep your lower back neutral. Squeeze at the peak.",
    alternatives: ["db_row", "barbell_row"],
    tags: ["back", "pull", "cable"],
  },
  {
    id: "face_pull",
    name: "Face Pull",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["traps", "back"],
    equipment: ["cable"],
    difficulty: "beginner",
    movementPattern: "pull",
    category: "isolation",
    instructions: "Cable at face height with rope attachment. Pull toward your face, flaring elbows out.",
    tips: "Great for shoulder health and rear delt development. Use light weight.",
    alternatives: ["rear_delt_fly"],
    tags: ["shoulders", "rear delt", "cable"],
  },
  {
    id: "machine_row",
    name: "Machine Row",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps"],
    equipment: ["machine"],
    difficulty: "beginner",
    movementPattern: "pull",
    category: "compound",
    instructions: "Sit in machine, chest against pad. Pull handles to your chest, squeezing shoulder blades together.",
    tips: "Stable and beginner-friendly. Good for learning the rowing movement pattern.",
    alternatives: ["seated_cable_row", "db_row"],
    tags: ["back", "pull", "machine"],
  },
  {
    id: "straight_arm_pulldown",
    name: "Straight Arm Pulldown",
    primaryMuscle: "back",
    secondaryMuscles: ["core"],
    equipment: ["cable"],
    difficulty: "beginner",
    movementPattern: "pull",
    category: "isolation",
    instructions: "Stand facing cable, arms extended overhead. Pull bar down to hips, keeping arms straight.",
    tips: "Excellent lat isolation that doesn't involve the biceps.",
    alternatives: ["lat_pulldown"],
    tags: ["back", "lats", "cable", "isolation"],
  },

  // ─── SHOULDERS ────────────────────────────────────────────
  {
    id: "ohp",
    name: "Overhead Press",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["triceps", "traps", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    movementPattern: "push",
    category: "compound",
    instructions: "Bar at shoulder height, slightly narrow grip. Press overhead until arms are fully extended. Lower with control.",
    tips: "Brace your core hard. Don't hyperextend your lower back.",
    alternatives: ["db_shoulder_press", "arnold_press"],
    tags: ["shoulders", "push", "compound"],
  },
  {
    id: "db_shoulder_press",
    name: "Dumbbell Shoulder Press",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    movementPattern: "push",
    category: "compound",
    instructions: "Seated or standing, press dumbbells from shoulder height to overhead.",
    tips: "Allows independent arm movement — great for identifying and fixing imbalances.",
    alternatives: ["ohp", "arnold_press", "machine_shoulder_press"],
    tags: ["shoulders", "push", "compound"],
  },
  {
    id: "lateral_raise",
    name: "Lateral Raise",
    primaryMuscle: "shoulders",
    secondaryMuscles: [],
    equipment: ["dumbbell", "cable"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Stand with dumbbells at sides. Raise arms out to the side to shoulder height, with a slight forward lean.",
    tips: "The best exercise for building wider shoulders. Don't swing. Use controlled tempo.",
    alternatives: ["cable_lateral_raise"],
    tags: ["shoulders", "side delts", "isolation"],
  },
  {
    id: "rear_delt_fly",
    name: "Rear Delt Fly",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["traps", "back"],
    equipment: ["dumbbell", "cable", "machine"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Hinge forward, arms hanging. Raise arms out to the sides, squeezing your rear delts.",
    tips: "Crucial for shoulder health and posture. Most people neglect this muscle.",
    alternatives: ["face_pull"],
    tags: ["shoulders", "rear delts", "isolation"],
  },
  {
    id: "arnold_press",
    name: "Arnold Press",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbell"],
    difficulty: "intermediate",
    movementPattern: "push",
    category: "compound",
    instructions: "Start with palms facing you. As you press up, rotate palms forward. Reverse on the way down.",
    tips: "Hits all three heads of the deltoid. Named after Arnold Schwarzenegger.",
    alternatives: ["db_shoulder_press", "ohp"],
    tags: ["shoulders", "push", "compound"],
  },
  {
    id: "machine_shoulder_press",
    name: "Machine Shoulder Press",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: ["machine"],
    difficulty: "beginner",
    movementPattern: "push",
    category: "compound",
    instructions: "Adjust seat and handles to appropriate height. Press overhead.",
    tips: "Great for beginners learning the overhead pressing pattern.",
    alternatives: ["db_shoulder_press", "ohp"],
    tags: ["shoulders", "push", "machine"],
  },

  // ─── BICEPS ───────────────────────────────────────────────
  {
    id: "barbell_curl",
    name: "Barbell Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: ["barbell"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Underhand grip, elbows at sides. Curl the bar up, keeping upper arms stationary.",
    tips: "Don't swing. Keep elbows pinned to your sides throughout.",
    alternatives: ["db_curl", "ez_bar_curl", "cable_curl"],
    tags: ["biceps", "isolation"],
  },
  {
    id: "db_curl",
    name: "Dumbbell Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Alternate or simultaneously curl dumbbells up, rotating wrist as you curl.",
    tips: "Supinate (rotate palm up) at the top for maximum bicep contraction.",
    alternatives: ["barbell_curl", "hammer_curl", "cable_curl"],
    tags: ["biceps", "isolation"],
  },
  {
    id: "hammer_curl",
    name: "Hammer Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Neutral grip (thumbs up), curl dumbbells up. Works the brachialis and brachioradialis.",
    tips: "Great for forearm and arm thickness. Can use heavier weight than regular curls.",
    alternatives: ["db_curl", "cable_curl"],
    tags: ["biceps", "forearms", "isolation"],
  },
  {
    id: "incline_db_curl",
    name: "Incline Dumbbell Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    difficulty: "intermediate",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Set bench to 45-60°. Arms hang freely behind you. Curl from the stretched position.",
    tips: "Increases the stretch on the biceps long head. Excellent for peak development.",
    alternatives: ["db_curl", "cable_curl"],
    tags: ["biceps", "isolation"],
  },
  {
    id: "cable_curl",
    name: "Cable Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: [],
    equipment: ["cable"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Low cable, underhand grip. Curl up, maintaining constant tension.",
    tips: "Constant tension throughout — can't rest at the top like with dumbbells.",
    alternatives: ["barbell_curl", "db_curl"],
    tags: ["biceps", "cable", "isolation"],
  },
  {
    id: "preacher_curl",
    name: "Preacher Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: [],
    equipment: ["barbell", "machine", "dumbbell"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Arms resting on preacher bench pad. Curl up, lower fully for full stretch.",
    tips: "Eliminates cheating — forces strict form. Great for building bicep peak.",
    alternatives: ["barbell_curl", "cable_curl"],
    tags: ["biceps", "isolation"],
  },

  // ─── TRICEPS ──────────────────────────────────────────────
  {
    id: "close_grip_bench",
    name: "Close Grip Bench Press",
    primaryMuscle: "triceps",
    secondaryMuscles: ["chest", "shoulders"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    movementPattern: "push",
    category: "compound",
    instructions: "Narrow grip (shoulder-width), lower bar to lower chest, press up.",
    tips: "Best compound movement for triceps mass. Don't go too narrow — shoulder-width is ideal.",
    alternatives: ["tricep_dip", "skull_crusher"],
    tags: ["triceps", "compound", "push"],
  },
  {
    id: "skull_crusher",
    name: "Skull Crushers",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: ["barbell", "dumbbell"],
    difficulty: "intermediate",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Lie on bench, bar above face. Lower bar toward forehead by bending elbows, press back up.",
    tips: "Keep upper arms perpendicular to floor. EZ bar is easier on the wrists.",
    alternatives: ["overhead_ext", "tricep_pushdown"],
    tags: ["triceps", "isolation"],
  },
  {
    id: "tricep_pushdown",
    name: "Tricep Pushdown",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: ["cable"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "High cable with bar or rope. Keep elbows at sides, push down until arms are straight.",
    tips: "Keep elbows pinned to your sides. Don't let them flare out.",
    alternatives: ["overhead_ext", "skull_crusher"],
    tags: ["triceps", "cable", "isolation"],
  },
  {
    id: "overhead_ext",
    name: "Overhead Tricep Extension",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: ["dumbbell", "cable"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Hold dumbbell or cable overhead. Lower behind head, press back up.",
    tips: "Stretches the long head of the triceps — crucial for full development.",
    alternatives: ["skull_crusher", "tricep_pushdown"],
    tags: ["triceps", "isolation"],
  },
  {
    id: "tricep_dip",
    name: "Tricep Dips",
    primaryMuscle: "triceps",
    secondaryMuscles: ["chest", "shoulders"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    movementPattern: "push",
    category: "compound",
    instructions: "Hands on parallel bars, body upright. Lower until arms are at 90°, press back up.",
    tips: "Keep torso upright to emphasize triceps over chest.",
    alternatives: ["close_grip_bench", "tricep_pushdown"],
    tags: ["triceps", "bodyweight", "push"],
  },
  {
    id: "diamond_pushup",
    name: "Diamond Push Up",
    primaryMuscle: "triceps",
    secondaryMuscles: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    movementPattern: "push",
    category: "compound",
    instructions: "Form a diamond shape with thumbs and forefingers. Lower chest to hands, press up.",
    tips: "Great bodyweight tricep exercise. Hard if you don't have access to a gym.",
    alternatives: ["push_up", "tricep_dip"],
    tags: ["triceps", "bodyweight"],
  },

  // ─── QUADS ────────────────────────────────────────────────
  {
    id: "barbell_squat",
    name: "Barbell Back Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    movementPattern: "squat",
    category: "compound",
    instructions: "Bar on traps, feet shoulder-width. Squat down until thighs are parallel to floor. Drive up through heels.",
    tips: "The king of leg exercises. Keep chest up and knees tracking over toes.",
    alternatives: ["goblet_squat", "leg_press", "bulgarian_split"],
    tags: ["quads", "squat", "compound", "full body"],
  },
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "core"],
    equipment: ["dumbbell", "kettlebell"],
    difficulty: "beginner",
    movementPattern: "squat",
    category: "compound",
    instructions: "Hold dumbbell/kettlebell at chest. Squat down, keeping chest tall and elbows inside knees.",
    tips: "Excellent for beginners learning squat form. Easy on the lower back.",
    alternatives: ["barbell_squat", "leg_press"],
    tags: ["quads", "squat", "beginner"],
  },
  {
    id: "leg_press",
    name: "Leg Press",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["machine"],
    difficulty: "beginner",
    movementPattern: "squat",
    category: "compound",
    instructions: "Feet on platform shoulder-width. Lower until knees are at 90°, press back up.",
    tips: "Safe for beginners and those with balance issues. High feet placement targets glutes more.",
    alternatives: ["barbell_squat", "goblet_squat"],
    tags: ["quads", "machine", "compound"],
  },
  {
    id: "hack_squat",
    name: "Hack Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes"],
    equipment: ["machine"],
    difficulty: "intermediate",
    movementPattern: "squat",
    category: "compound",
    instructions: "Place shoulders under pads, feet low on platform. Lower and drive back up.",
    tips: "More quad-focused than leg press. A great alternative to barbell squats.",
    alternatives: ["barbell_squat", "leg_press"],
    tags: ["quads", "machine", "compound"],
  },
  {
    id: "bulgarian_split",
    name: "Bulgarian Split Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["dumbbell", "barbell", "bodyweight"],
    difficulty: "intermediate",
    movementPattern: "squat",
    category: "compound",
    instructions: "Rear foot elevated on bench, hold dumbbells. Lower front knee toward floor, drive back up.",
    tips: "One of the best leg exercises. Harder than it looks — start with bodyweight.",
    alternatives: ["lunge", "barbell_squat"],
    tags: ["quads", "glutes", "unilateral", "compound"],
  },
  {
    id: "lunge",
    name: "Walking Lunge",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["bodyweight", "dumbbell"],
    difficulty: "beginner",
    movementPattern: "squat",
    category: "compound",
    instructions: "Step forward, lower back knee toward floor. Alternate legs walking forward.",
    tips: "Great for coordination and balance. Keep your torso upright.",
    alternatives: ["bulgarian_split", "goblet_squat"],
    tags: ["quads", "glutes", "compound"],
  },
  {
    id: "leg_extension",
    name: "Leg Extension",
    primaryMuscle: "quads",
    secondaryMuscles: [],
    equipment: ["machine"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Sit in machine, leg pad on ankles. Extend legs until straight, lower with control.",
    tips: "Best quad isolation exercise. Great as a finisher after compound movements.",
    alternatives: [],
    tags: ["quads", "isolation", "machine"],
  },

  // ─── HAMSTRINGS ───────────────────────────────────────────
  {
    id: "leg_curl",
    name: "Lying Leg Curl",
    primaryMuscle: "hamstrings",
    secondaryMuscles: [],
    equipment: ["machine"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Lie face down on machine, leg pad on ankles. Curl heels toward glutes, lower with control.",
    tips: "Best hamstring isolation exercise. Point toes for more bicep femoris activation.",
    alternatives: ["rdl", "nordic_curl"],
    tags: ["hamstrings", "isolation", "machine"],
  },
  {
    id: "nordic_curl",
    name: "Nordic Curl",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    movementPattern: "hinge",
    category: "compound",
    instructions: "Anchor feet, start kneeling upright. Lower your body forward as slowly as possible, use arms to catch yourself. Pull back up.",
    tips: "One of the best exercises for hamstring injury prevention. Very challenging.",
    alternatives: ["leg_curl", "rdl"],
    tags: ["hamstrings", "bodyweight", "advanced"],
  },
  {
    id: "good_morning",
    name: "Good Morning",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["back", "glutes"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    movementPattern: "hinge",
    category: "compound",
    instructions: "Bar on traps, hinge at hips pushing them back. Lower torso until parallel to floor, drive hips forward to stand.",
    tips: "Use light weight. Focus on feeling the hamstring stretch.",
    alternatives: ["rdl", "leg_curl"],
    tags: ["hamstrings", "hinge", "compound"],
  },

  // ─── GLUTES ───────────────────────────────────────────────
  {
    id: "hip_thrust",
    name: "Barbell Hip Thrust",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings", "quads"],
    equipment: ["barbell"],
    difficulty: "beginner",
    movementPattern: "hinge",
    category: "compound",
    instructions: "Upper back on bench, bar on hips. Drive hips up until body is straight, squeeze glutes at top.",
    tips: "The most effective glute exercise. Drive through your heels.",
    alternatives: ["glute_bridge", "rdl"],
    tags: ["glutes", "hinge", "compound"],
  },
  {
    id: "glute_bridge",
    name: "Glute Bridge",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings"],
    equipment: ["bodyweight", "dumbbell"],
    difficulty: "beginner",
    movementPattern: "hinge",
    category: "compound",
    instructions: "Lie on floor, knees bent. Drive hips up, squeezing glutes hard at the top.",
    tips: "Bodyweight version of hip thrust. Great for beginners or when equipment is limited.",
    alternatives: ["hip_thrust"],
    tags: ["glutes", "bodyweight", "hinge"],
  },
  {
    id: "cable_kickback",
    name: "Cable Kickback",
    primaryMuscle: "glutes",
    secondaryMuscles: [],
    equipment: ["cable"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Attach ankle strap to low cable. Kick leg back and up, squeezing glute at top.",
    tips: "Good glute isolation exercise. Control the return to maximize time under tension.",
    alternatives: ["glute_bridge", "hip_thrust"],
    tags: ["glutes", "cable", "isolation"],
  },
  {
    id: "step_up",
    name: "Step Up",
    primaryMuscle: "glutes",
    secondaryMuscles: ["quads", "hamstrings"],
    equipment: ["bodyweight", "dumbbell"],
    difficulty: "beginner",
    movementPattern: "squat",
    category: "compound",
    instructions: "Hold dumbbells, step onto a box with one foot. Drive through heel to stand on box, lower back down.",
    tips: "Height of the box determines emphasis — higher targets glutes more.",
    alternatives: ["lunge", "bulgarian_split"],
    tags: ["glutes", "quads", "unilateral"],
  },

  // ─── CALVES ───────────────────────────────────────────────
  {
    id: "standing_calf_raise",
    name: "Standing Calf Raise",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    equipment: ["machine", "bodyweight"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Balls of feet on edge, lower heels all the way down, then rise as high as possible.",
    tips: "Full range of motion is critical. Go all the way down for maximum stretch.",
    alternatives: ["seated_calf_raise"],
    tags: ["calves", "isolation"],
  },
  {
    id: "seated_calf_raise",
    name: "Seated Calf Raise",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    equipment: ["machine"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Sit in machine, pad on knees. Lower heels down, raise up on balls of feet.",
    tips: "Targets the soleus (under the gastrocnemius). Complement standing raises.",
    alternatives: ["standing_calf_raise"],
    tags: ["calves", "isolation", "machine"],
  },

  // ─── CORE ─────────────────────────────────────────────────
  {
    id: "plank",
    name: "Plank",
    primaryMuscle: "core",
    secondaryMuscles: ["shoulders"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Forearms on floor, body in a straight line. Hold for time.",
    tips: "Squeeze everything — glutes, quads, abs. Don't let hips sag.",
    alternatives: ["dead_bug", "ab_wheel"],
    tags: ["core", "bodyweight", "isometric"],
  },
  {
    id: "dead_bug",
    name: "Dead Bug",
    primaryMuscle: "core",
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Lie on back, arms up, knees at 90°. Extend opposite arm and leg, keeping lower back pressed to floor.",
    tips: "One of the best core stability exercises. Press your lower back into the floor throughout.",
    alternatives: ["plank", "ab_wheel"],
    tags: ["core", "bodyweight", "stability"],
  },
  {
    id: "ab_wheel",
    name: "Ab Wheel Rollout",
    primaryMuscle: "core",
    secondaryMuscles: ["back", "shoulders"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Kneel holding wheel. Roll out as far as you can without arching, pull back.",
    tips: "Very demanding. Start with partial range of motion until strong enough for full rollouts.",
    alternatives: ["plank", "cable_crunch"],
    tags: ["core", "advanced"],
  },
  {
    id: "hanging_leg_raise",
    name: "Hanging Leg Raise",
    primaryMuscle: "core",
    secondaryMuscles: ["core"],
    equipment: ["pullup_bar"],
    difficulty: "intermediate",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Hang from bar. Raise legs until perpendicular to torso, lower with control.",
    tips: "Don't swing. Control the descent. Bend knees to make it easier.",
    alternatives: ["plank", "cable_crunch"],
    tags: ["core", "pullup_bar"],
  },
  {
    id: "cable_crunch",
    name: "Cable Crunch",
    primaryMuscle: "core",
    secondaryMuscles: [],
    equipment: ["cable"],
    difficulty: "beginner",
    movementPattern: "isolation",
    category: "isolation",
    instructions: "Kneel at high cable with rope. Crunch elbows toward knees, really contracting the abs.",
    tips: "One of the few exercises that loads the abs through a full range of motion.",
    alternatives: ["plank", "hanging_leg_raise"],
    tags: ["core", "cable", "isolation"],
  },
];

// Map from UserEquipment to allowed Equipment types
export const EQUIPMENT_MAP: Record<UserEquipment, Equipment[]> = {
  full_gym: ["barbell", "dumbbell", "cable", "machine", "bodyweight", "kettlebell", "bands", "pullup_bar"],
  dumbbells_only: ["dumbbell", "bodyweight", "bands", "kettlebell"],
  home_gym: ["dumbbell", "bodyweight", "bands", "kettlebell", "pullup_bar"],
  bodyweight_only: ["bodyweight", "pullup_bar"],
};

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}

export function getExercisesByMuscle(muscle: MuscleGroup): Exercise[] {
  return EXERCISES.filter(
    (e) => e.primaryMuscle === muscle || e.secondaryMuscles.includes(muscle)
  );
}

export function filterExercisesByEquipment(
  exercises: Exercise[],
  userEquipment: UserEquipment
): Exercise[] {
  const allowed = EQUIPMENT_MAP[userEquipment];
  return exercises.filter((e) =>
    e.equipment.some((eq) => allowed.includes(eq))
  );
}

export function getAlternatives(exerciseId: string, userEquipment: UserEquipment): Exercise[] {
  const exercise = getExerciseById(exerciseId);
  if (!exercise) return [];
  const allowed = EQUIPMENT_MAP[userEquipment];
  return exercise.alternatives
    .map((id) => getExerciseById(id))
    .filter((e): e is Exercise => !!e && e.equipment.some((eq) => allowed.includes(eq)));
}

export function getSimilarityScore(exercise1: Exercise, exercise2: Exercise): number {
  let score = 0;
  if (exercise1.primaryMuscle === exercise2.primaryMuscle) score += 40;
  if (exercise1.movementPattern === exercise2.movementPattern) score += 20;
  if (exercise1.category === exercise2.category) score += 20;
  const sharedSecondary = exercise1.secondaryMuscles.filter((m) =>
    exercise2.secondaryMuscles.includes(m)
  );
  score += sharedSecondary.length * 10;
  return Math.min(score, 100);
}
